### ISSUE TITLE
ToolBox is missing

### ISSUE THREAD

**Issue by yaniv4345** [rvojcik/rt-server-client#11]
When running python system-info.py it throws an exception about ToolBox:
  Traceback (most recent call last):
    File "system-info.py", line 66, in <module>
      from ToolBox import net, dell
  ImportError: No module named ToolBox
 for some reason this package isn't in pip / yum

OS CentOS Linux release 7.2.1511 (Core)
Python version 2.7.5

**Comment by rvojcik** [comment]
I believe it's fixed now
