### ISSUE TITLE
/opt/server-audit/get-bios-ident.py missing

### ISSUE THREAD

**Issue by Snowman-25** [rvojcik/rt-server-client#14]
Hey,

I'm running RackTables 20.14 on CentOS 7.
When running ./system-info.py I get the following (anonymized) output:
`Hostname server.domain.de already exist. I'm using service tag: sh: /opt/server-audit/get-bios-ident.py: No such file or directory`
I couldn't find any reference to __get-bios-ident.py__ on the internet except in your code here.

Where can I get that?

**Comment by emilkrueper** [comment]
@Snowman-25 , I am having the same problem. Did you somehow make it already ?

**Comment by rvojcik** [comment]
I believe I fixed it yesterday, please try. 
I change path to script and also add missing script.

**Comment by emilkrueper** [comment]
Hi @rvojcik , that fixed this issue for me, thank you for taking a look into this.

**Comment by rvojcik** [comment]
Ok , perfect. I'm closing this.
