### ISSUE TITLE
Problem with first installation

### ISSUE THREAD

**Issue by emilkrueper** [rvojcik/rt-server-client#15]
root@test:/opt/test1/test_build# ./system-info.py
Traceback (most recent call last):
  File "./system-info.py", line 399, in <module>
    rtobject.InsertAttribute(object_id,server_type_id,rtobject.GetAttributeId("CPU Model"),cpu_model_name,"NULL",hostname)
  File "./lib/rtapi/__init__.py", line 203, in InsertAttribute
    sql = "SELECT string_value,uint_value FROM AttributeValue WHERE object_id = %d AND object_tid = %d AND attr_id = %d" % (object_id, object_tid, attr_id)
TypeError: %d format: a number is required, not NoneType

I have adjusted the config accordingly, something I am missing?

**Comment by emilkrueper** [comment]
@rvojcik , can you imagine where this is coming from? I started over with your last commit and the error is the same.

**Comment by unipanic** [comment]
I'm having this same issue, but at Installation Date:

Traceback (most recent call last):
  File "./system-info.py", line 500, in <module>
    result = rtobject.GetAttributeValue(object_id, rtobject.GetAttributeId("Installation Date"))
  File "./lib/rtapi/__init__.py", line 259, in GetAttributeValue
    sql = "SELECT string_value,uint_value,float_value FROM AttributeValue WHERE object_id = %d AND attr_id = %d" % (object_id, attr_id)
TypeError: %d format: a number is required, not NoneType

**Comment by rvojcik** [comment]
Hi guys, I have to create some installation script. I merge code from our production to opensource and sometimes there is fields I use in production but you dont have them in racktables.
There is 2 possible solutions.

1. Comment out the lines where inserting missing attribute
2. Create attribute in racktables and assign it to server. For these errors you have to create new Server attribute "Installation Date" and "CPU Model" in racktables cofiguration menu

I hope this helps. In new release a create installation script which checks all missing attributes.

**Comment by rvojcik** [comment]
Configuration -> Attributes -> (Edit Attributes | Edit Map)

**Comment by emilkrueper** [comment]
Hello @rvojcik and thank you for helping out. I added these two attributes in the racktables and now I receive this error instead.
```
/opt/rt-server-client# ./system-info.py 
Traceback (most recent call last):
  File "./system-info.py", line 399, in <module>
    rtobject.InsertAttribute(object_id,server_type_id,rtobject.GetAttributeId("CPU Model"),cpu_model_name,"NULL",hostname)
  File "./lib/rtapi/__init__.py", line 242, in InsertAttribute
    self.db_insert(sql)
  File "./lib/rtapi/__init__.py", line 67, in db_insert
    self.dbresult.execute(sql)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`racktables_db`.`AttributeValue`, CONSTRAINT `AttributeValue-FK-map` FOREIGN KEY (`object_tid`, `attr_id`) REFERENCES `AttributeMap` (`objtype_id`, `attr_id`))')

```

**Comment by rvojcik** [comment]
Perfect, you need add all these attributes

- "CPU Model"
- "CPUs Logical"
- "CPUs"
- "Cores per CPU"
- "CPU, MHz"
- "RAM Mem, MB"
- "Installation Date"
- "Kernel"

**Comment by emilkrueper** [comment]
I added those attributes as you advised as well, the error is the same, though.
