### ISSUE TITLE
Hostname <> already exist. I'm using service tag: ERROR:  Problem during executing dmidecode

### ISSUE THREAD

**Issue by max2505** [rvojcik/rt-server-client#16]
When running the script after the initial installation on a host (which is already in the object list), I'm getting the following error:

**Hostname racktablespc already exist. I'm using service tag: ERROR:  Problem during executing dmidecode**

**Comment by rvojcik** [comment]
Hi, 
thank you for your response. It's problem of the utility dmidecode (you have to install it in your system, it's often par of dmidecode package).
This project works in way where it combine hostname with ServiceTag(AssetTag in Racktables) to identify the host.

The message you get, consist of two separate information.

1. `Hostname racktablespc already exist`, this means that server racktablespc already exist in racktables database, but have different AssetTag, this is becouse of 2.

2. Out script is not able to get ServiceTag from server becouse it missing dmidecode utility, you have to install it into your system.

In that case AssetTag(racktables) = ServiceTag = Serial Number from dmidecode
Asset tag with hostname must match the real server, becouse it need to be sure that it's not rewriting some other server in racktables. So in your case you propably will need to delete whole host from racktables or manualy edit AssetTag field in racktables, to match the real server.
