### ISSUE TITLE
Code optimalization, debug

### ISSUE THREAD

**Issue by rvojcik** [rvojcik/rt-server-client#4]
- rewrite duplicated peace of codes
- add debug option
- check for dependencies and auto disable functions which requires them
- add option "init attributes" - add option which check for required custom attributes and add them

**Comment by ddcrjlalumiere** [comment]
Pull request https://github.com/rvojcik/rt-server-client/pull/9 includes a "--debug" flag and some code deduplication among its changes. Adding new debug lines is trivial in the new implementation.
