### ISSUE TITLE
Script does not update the SW Type for Ubuntu systems

### ISSUE THREAD

**Issue by bcsmith-fs** [rvojcik/rt-server-client#6]
SW Type never is updated on ubuntu servers, I will debug to figure out the issue but I believe it has to do with os_codename as the query rather than os_version. I switch that but get a database duplicate error if the SW Type is set and a constraint error if it does not.

**Comment by rvojcik** [comment]
Hi, SW is paired with racktables dictionary, make sure that your racktables have your system in dictionary. Racktables->Configuration->Dictionary-server OS type

**Comment by bcsmith-fs** [comment]
Yes the Dictionary attributes are there, for example Ubuntu 14.04 has 
uint_value of 2109.  So if I select the AttributeValue Field for a host 
that already has the SW Type set I get:

mysql> select * from AttributeValue where object_id = 182 AND attr_id = 4;
+-----------+------------+---------+--------------+------------+-------------+
| object_id | object_tid | attr_id | string_value | uint_value | 
float_value |
+-----------+------------+---------+--------------+------------+-------------+
|       182 |       1504 |       4 | NULL         |       2109 |        
NULL |
+-----------+------------+---------+--------------+------------+-------------+


On 1/30/15 9:58 AM, Robert Vojcik wrote:
>
> Hi, SW is paired with racktables dictionary, make sure that your 
> racktables have your system in dictionary. 
> Racktables->Configuration->Dictionary-server OS type
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rvojcik/rt-server-client/issues/6#issuecomment-72213252>.
>

-- 

Brian Smith| System Administrator II |Information & Media 
Technology|Full Sail University

T407.462.3303

**Comment by bcsmith-fs** [comment]
mysql> select * from Dictionary where dict_value like 'Ubuntu%';
+------------+----------+-------------+-------------------------------+
| chapter_id | dict_key | dict_sticky | dict_value                    |
+------------+----------+-------------+-------------------------------+
|         13 |     1704 | yes         | Ubuntu%GSKIP%Ubuntu 10.04 LTS |
|         13 |     1705 | yes         | Ubuntu%GSKIP%Ubuntu 10.10     |
|         13 |     1706 | yes         | Ubuntu%GSKIP%Ubuntu 11.04     |
|         13 |     1707 | yes         | Ubuntu%GSKIP%Ubuntu 11.10     |
|         13 |     1708 | yes         | Ubuntu%GSKIP%Ubuntu 12.04 LTS |
|         13 |     1813 | yes         | Ubuntu%GSKIP%Ubuntu 12.10     |
|         13 |     2107 | yes         | Ubuntu%GSKIP%Ubuntu 13.04     |
|         13 |     2108 | yes         | Ubuntu%GSKIP%Ubuntu 13.10     |
|         13 |     2109 | yes         | Ubuntu%GSKIP%Ubuntu 14.04 LTS |
|         13 |      428 | yes         | Ubuntu%GSKIP%Ubuntu 4.10      |
|         13 |      429 | yes         | Ubuntu%GSKIP%Ubuntu 5.04      |
|         13 |      430 | yes         | Ubuntu%GSKIP%Ubuntu 5.10      |
|         13 |      431 | yes         | Ubuntu%GSKIP%Ubuntu 6.06 LTS  |
|         13 |      432 | yes         | Ubuntu%GSKIP%Ubuntu 6.10      |
|         13 |      433 | yes         | Ubuntu%GSKIP%Ubuntu 7.04      |
|         13 |      434 | yes         | Ubuntu%GSKIP%Ubuntu 7.10      |
|         13 |      435 | yes         | Ubuntu%GSKIP%Ubuntu 8.04 LTS  |
|         13 |      796 | yes         | Ubuntu%GSKIP%Ubuntu 8.10      |
|         13 |     1054 | yes         | Ubuntu%GSKIP%Ubuntu 9.04      |
|         13 |     1320 | yes         | Ubuntu%GSKIP%Ubuntu 9.10      |
+------------+----------+-------------+-------------------------------+
20 rows in set (0.00 sec)
On 1/30/15 10:02 AM, Brian Smith wrote:
> Yes the Dictionary attributes are there, for example Ubuntu 14.04 has 
> uint_value of 2109.  So if I select the AttributeValue Field for a 
> host that already has the SW Type set I get:
>
> mysql> select * from AttributeValue where object_id = 182 AND attr_id = 4;
> +-----------+------------+---------+--------------+------------+-------------+
> | object_id | object_tid | attr_id | string_value | uint_value | 
> float_value |
> +-----------+------------+---------+--------------+------------+-------------+
> |       182 |       1504 |       4 | NULL         |       2109 
> |        NULL |
> +-----------+------------+---------+--------------+------------+-------------+
>
>
> On 1/30/15 9:58 AM, Robert Vojcik wrote:
>>
>> Hi, SW is paired with racktables dictionary, make sure that your 
>> racktables have your system in dictionary. 
>> Racktables->Configuration->Dictionary-server OS type
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/rvojcik/rt-server-client/issues/6#issuecomment-72213252>.
>>
>
> -- 
>
> Brian Smith| System Administrator II |Information & Media 
> Technology|Full Sail University
>
> T407.462.3303
>

-- 

Brian Smith| System Administrator II |Information & Media 
Technology|Full Sail University

T407.462.3303

**Comment by rvojcik** [comment]
Looks like script is looking for string 'Ubuntu trusty', not Ubuntu 14.04 LTS.

Just try to add 'Ubuntu%GSKIP%Ubuntu trusty' for test. If it will work we can make some exeption for Ubuntu and change search string.

**Comment by bcsmith-fs** [comment]
Yes I was thinking instead of os_codename use os_version for the search 
it might work as well.

On 1/30/15 10:09 AM, Robert Vojcik wrote:
>
> Looks like script is looking for string 'Ubuntu trusty', not Ubuntu 
> 14.04 LTS.
>
> Just try to add 'Ubuntu%GSKIP%Ubuntu trusty' for test. If it will work 
> we can make some exeption for Ubuntu and change search string.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rvojcik/rt-server-client/issues/6#issuecomment-72214933>.
>

-- 

Brian Smith| System Administrator II |Information & Media 
Technology|Full Sail University

T407.462.3303

**Comment by rvojcik** [comment]
Can you test it please ?

**Comment by bcsmith-fs** [comment]
I get the same error as if I change the check to os_version. Here's the 
test results:


mysql> UPDATE Dictionary SET dict_value = 'Ubuntu%GSKIP%Ubuntu trusty' 
where dict_key = 2109;
Query OK, 1 row affected (0.06 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from Dictionary where dict_value like 'Ubuntu%';
+------------+----------+-------------+-------------------------------+
| chapter_id | dict_key | dict_sticky | dict_value                    |
+------------+----------+-------------+-------------------------------+
|         13 |     1704 | yes         | Ubuntu%GSKIP%Ubuntu 10.04 LTS |
|         13 |     1705 | yes         | Ubuntu%GSKIP%Ubuntu 10.10     |
|         13 |     1706 | yes         | Ubuntu%GSKIP%Ubuntu 11.04     |
|         13 |     1707 | yes         | Ubuntu%GSKIP%Ubuntu 11.10     |
|         13 |     1708 | yes         | Ubuntu%GSKIP%Ubuntu 12.04 LTS |
|         13 |     1813 | yes         | Ubuntu%GSKIP%Ubuntu 12.10     |
|         13 |     2107 | yes         | Ubuntu%GSKIP%Ubuntu 13.04     |
|         13 |     2108 | yes         | Ubuntu%GSKIP%Ubuntu 13.10     |
|         13 |      428 | yes         | Ubuntu%GSKIP%Ubuntu 4.10      |
|         13 |      429 | yes         | Ubuntu%GSKIP%Ubuntu 5.04      |
|         13 |      430 | yes         | Ubuntu%GSKIP%Ubuntu 5.10      |
|         13 |      431 | yes         | Ubuntu%GSKIP%Ubuntu 6.06 LTS  |
|         13 |      432 | yes         | Ubuntu%GSKIP%Ubuntu 6.10      |
|         13 |      433 | yes         | Ubuntu%GSKIP%Ubuntu 7.04      |
|         13 |      434 | yes         | Ubuntu%GSKIP%Ubuntu 7.10      |
|         13 |      435 | yes         | Ubuntu%GSKIP%Ubuntu 8.04 LTS  |
|         13 |      796 | yes         | Ubuntu%GSKIP%Ubuntu 8.10      |
|         13 |     1054 | yes         | Ubuntu%GSKIP%Ubuntu 9.04      |
|         13 |     1320 | yes         | Ubuntu%GSKIP%Ubuntu 9.10      |
|         13 |     2109 | yes         | Ubuntu%GSKIP%Ubuntu trusty    |
+------------+----------+-------------+-------------------------------+
20 rows in set (0.00 sec)

mysql> \q
Bye
root@wpkfl-fs-racktables:/opt/rt-server-client# ./system-info.py
Traceback (most recent call last):
   File "./system-info.py", line 824, in <module>
InsertAttribute(object_id,server_type_id,attr_id,"NULL",os_id,hostname)
   File "./system-info.py", line 377, in InsertAttribute
     dbresult.execute(sql)
   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, 
in execute
     self.errorhandler(self, exc, value)
   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 
36, in defaulterrorhandler
     raise errorclass, errorvalue
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry '182-4' for 
key 'PRIMARY'")

On 1/30/15 10:49 AM, Robert Vojcik wrote:
>
> Can you test it please ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rvojcik/rt-server-client/issues/6#issuecomment-72221406>.
>

-- 

Brian Smith| System Administrator II |Information & Media 
Technology|Full Sail University

T407.462.3303

**Comment by bcsmith-fs** [comment]
That was with the value already set, If I remove it and run I get:

root@wpkfl-fs-racktables:/opt/rt-server-client# ./system-info.py
Traceback (most recent call last):
   File "./system-info.py", line 824, in <module>
InsertAttribute(object_id,server_type_id,attr_id,"NULL",os_id,hostname)
   File "./system-info.py", line 377, in InsertAttribute
     dbresult.execute(sql)
   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, 
in execute
     self.errorhandler(self, exc, value)
   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 
36, in defaulterrorhandler
     raise errorclass, errorvalue
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry '182-4' for 
key 'PRIMARY'")
root@wpkfl-fs-racktables:/opt/rt-server-client# ./system-info.py
Traceback (most recent call last):
   File "./system-info.py", line 824, in <module>
InsertAttribute(object_id,server_type_id,attr_id,"NULL",os_id,hostname)
   File "./system-info.py", line 377, in InsertAttribute
     dbresult.execute(sql)
   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, 
in execute
     self.errorhandler(self, exc, value)
   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 
36, in defaulterrorhandler
     raise errorclass, errorvalue
_mysql_exceptions.IntegrityError: (1452, 'Cannot add or update a child 
row: a foreign key constraint fails (`racktables_db`.`AttributeValue`, 
CONSTRAINT `AttributeValue-FK-object` FOREIGN KEY (`object_id`, 
`object_tid`) REFERENCES `Object` (`id`, `objtype_id`) ON DELETE CASCADE 
ON UPDATE CASCADE)')

On 1/30/15 11:02 AM, Brian Smith wrote:
> I get the same error as if I change the check to os_version. Here's 
> the test results:
>
>
> mysql> UPDATE Dictionary SET dict_value = 'Ubuntu%GSKIP%Ubuntu trusty' 
> where dict_key = 2109;
> Query OK, 1 row affected (0.06 sec)
> Rows matched: 1  Changed: 1  Warnings: 0
>
> mysql> select * from Dictionary where dict_value like 'Ubuntu%';
> +------------+----------+-------------+-------------------------------+
> | chapter_id | dict_key | dict_sticky | dict_value                    |
> +------------+----------+-------------+-------------------------------+
> |         13 |     1704 | yes         | Ubuntu%GSKIP%Ubuntu 10.04 LTS |
> |         13 |     1705 | yes         | Ubuntu%GSKIP%Ubuntu 10.10     |
> |         13 |     1706 | yes         | Ubuntu%GSKIP%Ubuntu 11.04     |
> |         13 |     1707 | yes         | Ubuntu%GSKIP%Ubuntu 11.10     |
> |         13 |     1708 | yes         | Ubuntu%GSKIP%Ubuntu 12.04 LTS |
> |         13 |     1813 | yes         | Ubuntu%GSKIP%Ubuntu 12.10     |
> |         13 |     2107 | yes         | Ubuntu%GSKIP%Ubuntu 13.04     |
> |         13 |     2108 | yes         | Ubuntu%GSKIP%Ubuntu 13.10     |
> |         13 |      428 | yes         | Ubuntu%GSKIP%Ubuntu 4.10      |
> |         13 |      429 | yes         | Ubuntu%GSKIP%Ubuntu 5.04      |
> |         13 |      430 | yes         | Ubuntu%GSKIP%Ubuntu 5.10      |
> |         13 |      431 | yes         | Ubuntu%GSKIP%Ubuntu 6.06 LTS  |
> |         13 |      432 | yes         | Ubuntu%GSKIP%Ubuntu 6.10      |
> |         13 |      433 | yes         | Ubuntu%GSKIP%Ubuntu 7.04      |
> |         13 |      434 | yes         | Ubuntu%GSKIP%Ubuntu 7.10      |
> |         13 |      435 | yes         | Ubuntu%GSKIP%Ubuntu 8.04 LTS  |
> |         13 |      796 | yes         | Ubuntu%GSKIP%Ubuntu 8.10      |
> |         13 |     1054 | yes         | Ubuntu%GSKIP%Ubuntu 9.04      |
> |         13 |     1320 | yes         | Ubuntu%GSKIP%Ubuntu 9.10      |
> |         13 |     2109 | yes         | Ubuntu%GSKIP%Ubuntu trusty    |
> +------------+----------+-------------+-------------------------------+
> 20 rows in set (0.00 sec)
>
> mysql> \q
> Bye
> root@wpkfl-fs-racktables:/opt/rt-server-client# ./system-info.py
> Traceback (most recent call last):
>   File "./system-info.py", line 824, in <module>
> InsertAttribute(object_id,server_type_id,attr_id,"NULL",os_id,hostname)
>   File "./system-info.py", line 377, in InsertAttribute
>     dbresult.execute(sql)
>   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 
> 174, in execute
>     self.errorhandler(self, exc, value)
>   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 
> 36, in defaulterrorhandler
>     raise errorclass, errorvalue
> _mysql_exceptions.IntegrityError: (1062, "Duplicate entry '182-4' for 
> key 'PRIMARY'")
>
> On 1/30/15 10:49 AM, Robert Vojcik wrote:
>>
>> Can you test it please ?
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/rvojcik/rt-server-client/issues/6#issuecomment-72221406>.
>>
>
> -- 
>
> Brian Smith| System Administrator II |Information & Media 
> Technology|Full Sail University
>
> T407.462.3303
>

-- 

Brian Smith| System Administrator II |Information & Media 
Technology|Full Sail University

T407.462.3303

**Comment by bcsmith-fs** [comment]
It seems the object_tid when the script runs is set to 4 but in the db 
is 1504 (If I set it manually through racktables). Looking deeper now 
but think I'm in the right direction to fix.


On 1/30/15 10:49 AM, Robert Vojcik wrote:
>
> Can you test it please ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rvojcik/rt-server-client/issues/6#issuecomment-72221406>.
>

-- 

Brian Smith| System Administrator II |Information & Media 
Technology|Full Sail University

T407.462.3303

**Comment by rvojcik** [comment]
I'm working on it. Preparing big new update using racktables api. You should try testing version in testing branch.

Clone project, then git checkout testing ; git submodule init ; git submodule update

**Comment by rvojcik** [comment]
OK, now I had same error, it's related with latest version of racktables, maybe some changes in db structure.

**Comment by bcsmith-fs** [comment]
Seems if the host exists but the os version is not the same it tries to 
add a new record rather than updating it to the correct os version 
causing a duplicate entry which fails. problem line is

         if os_id != None:
InsertAttribute(object_id,server_type_id,attr_id,"NULL",os_id,hostname)

On 1/30/15 3:42 PM, Robert Vojcik wrote:
>
> OK, now I had same error, it's related with latest version of 
> racktables, maybe some changes in db structure.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rvojcik/rt-server-client/issues/6#issuecomment-72266948>.
>

-- 

Brian Smith| System Administrator II |Information & Media 
Technology|Full Sail University

T407.462.3303

**Comment by bcsmith-fs** [comment]
Ok I will try that.

On 1/30/15 3:25 PM, Robert Vojcik wrote:
>
> I'm working on it. Preparing big new update using racktables api. You 
> should try testing version in testing branch.
>
> Clone project, then git checkout testing ; git submodule init ; git 
> submodule update
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rvojcik/rt-server-client/issues/6#issuecomment-72264864>.
>

-- 

Brian Smith| System Administrator II |Information & Media 
Technology|Full Sail University

T407.462.3303

**Comment by rvojcik** [comment]
Ok I think I have solution. In new version of racktables there is relation between attributes and attribute map.

So you have to Map our new attributes to Server and VM. (in configuration->Attributes->Map) 
When you assign attributes to object type it works.

In few next days I will prepare new update of rt-server-client to latest racktables.

**Comment by bcsmith-fs** [comment]
Which attributes are you setting there?

On 1/30/15 4:00 PM, Robert Vojcik wrote:
>
> Ok I think I have solution. In new version of racktables there is 
> relation between attributes and attribute map.
>
> So you have to Map our new attributes to Server and VM. (in 
> configuration->Attributes->Map)
> When you assign attributes to object type it works.
>
> In few next days I will prepare new update of rt-server-client to 
> latest racktables.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rvojcik/rt-server-client/issues/6#issuecomment-72269467>.
>

-- 

Brian Smith| System Administrator II |Information & Media 
Technology|Full Sail University

T407.462.3303

**Comment by rvojcik** [comment]
('string','HW support type'),
('string','CPU Model'),
('string','RAM Model'),
('uint','CPUs Logical'),
('uint','CPUs'),
('uint','Cores per CPU'),
('uint','RAM Mem, MB');
